blank_issues_enabled: false
contact_links:
  - name: ðŸ“œ Documentation
    url: https://docs.pixelfs.io
    about: Before submitting a question, please read the documentation. If you are still not satisfied, ask a question again.
  - name: ðŸ‘€ GitHub Discussions
    url: https://github.com/pixelfs/pixelfs/discussions
    about: If your issue is not a feature or bug, go to the discussion panel and retrieve if your issue already exists before submitting it.
